#!/usr/bin/env python3
"""Select a built CIS scanner image on the controller Function, or roll it back.

Requires Python 3.9+ and an authenticated OCI CLI; no Docker or Terraform required.
Preview is the default. Add --apply to change OCI. Only CIS_RUNNER_IMAGE changes;
all other function configuration values are preserved. The Function's own image
and the scan schedule are not changed. No scan is started automatically.

Use upgrade.json produced by upgrade_cis_scanner.py. After a verified --apply,
generate cis-scanner.auto.tfvars beside the record (or at --tfvars-output).
Keep that file with the deployment's Terraform configuration to retain the image.
"""
import argparse
import json
import re
import subprocess
import tempfile
import time
from pathlib import Path

KEY = "CIS_RUNNER_IMAGE"
TFVARS_HEADER = "# Generated by update_cis_scanner_config.py\n"


def check_tfvars(path):
    if path.is_symlink():
        raise ValueError("Refusing to overwrite a tfvars symlink.")
    if path.exists() and not re.fullmatch(
            re.escape(TFVARS_HEADER) + r'runner_image_uri = "[^"\n]+"\n', path.read_text()):
        raise ValueError(f"{path} is not generated by this script; choose another --tfvars-output.")


def write_tfvars(path, image):
    check_tfvars(path)
    temporary = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(mode="w", dir=path.parent, delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(TFVARS_HEADER + f'runner_image_uri = "{image}"\n')
        temporary.replace(path)
    except OSError as error:
        raise RuntimeError(f"OCI selects {image}, but writing {path} failed. Fix the path and rerun --apply to generate it.") from error
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    print(f"Generated: {path}\nKeep this file in the deployment's Terraform root configuration.")


def oci(args, *command):
    options = ["--region", args.region, "--output", "json"]
    if args.profile:
        options += ["--profile", args.profile]
    result = subprocess.run(["oci", *command, *options], text=True, capture_output=True, timeout=180)
    if result.returncode:
        # Avoid printing configuration values from the captured response.
        raise RuntimeError(f"OCI command failed (exit {result.returncode}). Check credentials, permissions, and live configuration.")
    return json.loads(result.stdout)


def update_command():
    # Support both the current OCI CLI and the older CLI used by some deployments.
    for command in (["fn", "function", "update", "container-function"], ["fn", "function", "update"]):
        help_result = subprocess.run(["oci", *command, "--help"], text=True, capture_output=True, timeout=30)
        if help_result.returncode == 0 and "--config" in help_result.stdout and "--if-match" in help_result.stdout:
            return command
    raise RuntimeError("OCI CLI has no supported function configuration update command.")


def image_repository(value, pinned=False):
    match = re.fullmatch(r"([a-z0-9][a-z0-9.:-]*/[a-z0-9][a-z0-9._/-]*)"
                         r"(@sha256:[0-9a-f]{64}|:[A-Za-z0-9_][A-Za-z0-9_.-]{0,127})", value)
    if not match or (pinned and not match[2].startswith("@sha256:")):
        raise ValueError("Expected a valid registry image URI; saved images must use digests.")
    return match[1]


def update(args):
    record = json.loads(args.record.read_text())
    old, new = record["previous_image"], record["new_image"]
    repository = image_repository(old, pinned=True)
    if image_repository(new, pinned=True) != repository:
        raise ValueError("Saved images do not belong to the same runner repository.")
    before = oci(args, "fn", "function", "get", "--function-id", args.function_id)
    data = before["data"]
    config = data.get("config", {})
    if data.get("lifecycle-state") != "ACTIVE" or KEY not in config:
        raise ValueError("Select the ACTIVE controller Function that has CIS_RUNNER_IMAGE configured.")
    current = config[KEY]
    target = new if args.action == "upgrade" else old
    tfvars = args.tfvars_output or args.record.parent / "cis-scanner.auto.tfvars"
    if args.apply:
        check_tfvars(tfvars)
    if image_repository(current) != repository:
        raise ValueError("This controller uses a different repository; check the function OCID and record.")
    if current == target:
        print(f"Already selected in OCI: {target}.")
        if args.apply:
            write_tfvars(tfvars, target)
        return
    if args.action == "rollback" and current != new:
        raise ValueError("Rollback record does not match the currently selected image; refusing to overwrite it.")
    if args.action == "upgrade" and "@sha256:" in current and current != old:
        raise ValueError("Current digest differs from the recorded previous image; check for a newer deployment.")
    print(f"Function: {args.function_id}\nRegion: {args.region}\nCurrent: {current}\nSelected: {target}", flush=True)
    if "@sha256:" not in current:
        print("Current selection is a tag; this script cannot verify whether that tag moved since the build.")
    if not args.apply:
        print("Preview only. Add --apply to update CIS_RUNNER_IMAGE.")
        return
    if not before.get("etag"):
        raise ValueError("Missing ETag; cannot protect against a concurrent function update.")

    # OCI config updates replace the map: send every existing value, changing one key.
    selected_config = {**config, KEY: target}
    with tempfile.TemporaryDirectory(prefix="cis-function-config-") as directory:
        config_file = Path(directory) / "config.json"
        config_file.write_text(json.dumps(selected_config))
        oci(args, *update_command(), "--function-id", args.function_id,
            "--config", f"file://{config_file}", "--if-match", before["etag"], "--force")

    # Read back the result; success here means configuration updated, not scan completed.
    for attempt in range(12):
        after = oci(args, "fn", "function", "get", "--function-id", args.function_id)["data"]
        if after.get("lifecycle-state") == "FAILED":
            raise RuntimeError("Function update failed. Inspect OCI work requests and current configuration.")
        if after.get("lifecycle-state") == "ACTIVE" and after.get("config", {}).get(KEY) == target:
            if after["config"] != selected_config or after.get("image") != data.get("image"):
                raise RuntimeError("Other settings changed during verification; inspect concurrent updates.")
            print("Verified. Subsequent scans will use the selected image.")
            write_tfvars(tfvars, target)
            return
        if attempt < 11:
            time.sleep(5)
    raise RuntimeError("Verification timed out; the update may have succeeded. Check live configuration before retrying.")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("action", choices=["upgrade", "rollback"])
    parser.add_argument("--record", type=Path, required=True, help="upgrade.json from the image build")
    parser.add_argument("--function-id", required=True, help="Controller Function OCID, not Container Instance OCID")
    parser.add_argument("--region", required=True)
    parser.add_argument("--profile", help="Optional OCI CLI profile")
    parser.add_argument("--apply", action="store_true", help="Perform the update; otherwise preview only")
    parser.add_argument("--tfvars-output", type=Path, help="Output path; default: cis-scanner.auto.tfvars beside upgrade.json")
    update(parser.parse_args())


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, RuntimeError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"ERROR: {error}")
