-- Core staging and configuration foundation for the OCI CIS POC.
-- This migration intentionally avoids lifecycle/business workflow tables; those
-- land after the shared-core vertical slice is reviewed.

CREATE TABLE scan_run (
    run_id VARCHAR2(128) NOT NULL,
    tenancy_id VARCHAR2(255) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    scanner_version VARCHAR2(100),
    scanner_commit VARCHAR2(100),
    wrapper_version VARCHAR2(100),
    benchmark_version VARCHAR2(100),
    requested_regions_json CLOB CHECK (requested_regions_json IS JSON),
    completed_regions_json CLOB CHECK (completed_regions_json IS JSON),
    manifest_checksum VARCHAR2(128),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_scan_run PRIMARY KEY (run_id),
    CONSTRAINT ck_scan_run_status CHECK (
        status IN ('SUCCESS', 'FAILED', 'PARTIAL', 'CANCELLED')
    )
);

CREATE TABLE scan_file (
    scan_file_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id VARCHAR2(128) NOT NULL,
    source_path VARCHAR2(1024) NOT NULL,
    category VARCHAR2(30) NOT NULL,
    file_format VARCHAR2(30) NOT NULL,
    checksum VARCHAR2(128) NOT NULL,
    size_bytes NUMBER NOT NULL,
    row_count NUMBER,
    schema_hash VARCHAR2(128),
    control_hint VARCHAR2(50),
    required_for_completeness CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_scan_file PRIMARY KEY (scan_file_id),
    CONSTRAINT fk_scan_file_run FOREIGN KEY (run_id)
        REFERENCES scan_run (run_id),
    CONSTRAINT uq_scan_file_run_path UNIQUE (run_id, source_path),
    CONSTRAINT ck_scan_file_required CHECK (required_for_completeness IN ('Y', 'N'))
);

CREATE TABLE raw_cis_record (
    raw_record_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id VARCHAR2(128) NOT NULL,
    scan_file_id NUMBER NOT NULL,
    source_row NUMBER NOT NULL,
    schema_hash VARCHAR2(128) NOT NULL,
    payload_json CLOB NOT NULL CHECK (payload_json IS JSON),
    record_checksum VARCHAR2(128) NOT NULL,
    loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_raw_cis_record PRIMARY KEY (raw_record_id),
    CONSTRAINT fk_raw_record_run FOREIGN KEY (run_id)
        REFERENCES scan_run (run_id),
    CONSTRAINT fk_raw_record_file FOREIGN KEY (scan_file_id)
        REFERENCES scan_file (scan_file_id),
    CONSTRAINT uq_raw_record_line UNIQUE (run_id, scan_file_id, source_row)
);

CREATE TABLE config_version (
    config_version_id VARCHAR2(128) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    activated_at TIMESTAMP WITH TIME ZONE,
    description VARCHAR2(1000),
    CONSTRAINT pk_config_version PRIMARY KEY (config_version_id),
    CONSTRAINT ck_config_version_status CHECK (
        status IN ('DRAFT', 'ACTIVE', 'RETIRED')
    )
);

CREATE TABLE source_profile (
    source_profile_id VARCHAR2(128) NOT NULL,
    config_version_id VARCHAR2(128) NOT NULL,
    display_name VARCHAR2(255) NOT NULL,
    schema_hash VARCHAR2(128) NOT NULL,
    required_headers_json CLOB NOT NULL CHECK (required_headers_json IS JSON),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_source_profile PRIMARY KEY (source_profile_id, config_version_id),
    CONSTRAINT fk_source_profile_config FOREIGN KEY (config_version_id)
        REFERENCES config_version (config_version_id)
);

CREATE TABLE field_alias (
    field_alias_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_profile_id VARCHAR2(128) NOT NULL,
    config_version_id VARCHAR2(128) NOT NULL,
    source_header VARCHAR2(255) NOT NULL,
    canonical_header VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_field_alias PRIMARY KEY (field_alias_id),
    CONSTRAINT fk_field_alias_profile FOREIGN KEY (source_profile_id, config_version_id)
        REFERENCES source_profile (source_profile_id, config_version_id),
    CONSTRAINT uq_field_alias UNIQUE (
        source_profile_id,
        config_version_id,
        source_header
    )
);

CREATE TABLE validation_rule (
    validation_rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_profile_id VARCHAR2(128) NOT NULL,
    config_version_id VARCHAR2(128) NOT NULL,
    rule_type VARCHAR2(80) NOT NULL,
    rule_config_json CLOB NOT NULL CHECK (rule_config_json IS JSON),
    severity VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_validation_rule PRIMARY KEY (validation_rule_id),
    CONSTRAINT fk_validation_rule_profile FOREIGN KEY (source_profile_id, config_version_id)
        REFERENCES source_profile (source_profile_id, config_version_id),
    CONSTRAINT ck_validation_rule_severity CHECK (
        severity IN ('INFO', 'WARN', 'ERROR', 'BLOCKING')
    )
);

CREATE INDEX ix_scan_file_run ON scan_file (run_id);
CREATE INDEX ix_raw_cis_record_run ON raw_cis_record (run_id);
CREATE INDEX ix_raw_cis_record_schema ON raw_cis_record (schema_hash);
