-- Canonical finding and observation foundation for the OCI CIS POC.
-- The wrapper derives staging/canonical_finding_stage.jsonl for canonical_finding_stage.
-- A reviewed upsert package will merge staged rows into canonical_finding and
-- finding_observation in the next database slice.

CREATE TABLE canonical_finding_stage (
    stage_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id VARCHAR2(128) NOT NULL,
    finding_id VARCHAR2(128) NOT NULL,
    source_file VARCHAR2(1024) NOT NULL,
    source_row NUMBER NOT NULL,
    canonical_json CLOB NOT NULL CHECK (canonical_json IS JSON),
    loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_canonical_finding_stage PRIMARY KEY (stage_id),
    CONSTRAINT fk_canonical_stage_run FOREIGN KEY (run_id)
        REFERENCES scan_run (run_id),
    CONSTRAINT uq_canonical_stage_source UNIQUE (
        run_id,
        finding_id,
        source_file,
        source_row
    )
);

CREATE TABLE canonical_finding (
    finding_id VARCHAR2(128) NOT NULL,
    tenancy_id VARCHAR2(255) NOT NULL,
    control_lineage_id VARCHAR2(255) NOT NULL,
    control_display_id VARCHAR2(80) NOT NULL,
    benchmark_version VARCHAR2(100) NOT NULL,
    scope_type VARCHAR2(40) NOT NULL,
    scope_key VARCHAR2(1024) NOT NULL,
    region VARCHAR2(100),
    region_key VARCHAR2(100) GENERATED ALWAYS AS (COALESCE(region, 'GLOBAL')) VIRTUAL,
    current_state VARCHAR2(40) NOT NULL,
    priority VARCHAR2(40) NOT NULL,
    risk_score NUMBER,
    owner VARCHAR2(255),
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_state_change_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    due_at TIMESTAMP WITH TIME ZONE,
    product_json CLOB CHECK (product_json IS JSON),
    resource_json CLOB CHECK (resource_json IS JSON),
    compartment_json CLOB NOT NULL CHECK (compartment_json IS JSON),
    attributes_json CLOB CHECK (attributes_json IS JSON),
    evidence_summary VARCHAR2(4000),
    remediation VARCHAR2(4000),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_canonical_finding PRIMARY KEY (finding_id),
    CONSTRAINT uq_canonical_finding_identity UNIQUE (
        tenancy_id,
        benchmark_version,
        control_display_id,
        scope_type,
        scope_key,
        region_key
    ),
    CONSTRAINT ck_canonical_finding_state CHECK (
        current_state IN (
            'NEW',
            'ACTIVE',
            'RESOLVED',
            'REOPENED',
            'ACCEPTED_RISK',
            'SUPPRESSED',
            'NOT_APPLICABLE',
            'NOT_ASSESSED',
            'DATA_ERROR'
        )
    ),
    CONSTRAINT ck_canonical_finding_priority CHECK (
        priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL')
    )
);

CREATE TABLE finding_observation (
    observation_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    finding_id VARCHAR2(128) NOT NULL,
    run_id VARCHAR2(128) NOT NULL,
    source_file VARCHAR2(1024) NOT NULL,
    source_row NUMBER NOT NULL,
    schema_hash VARCHAR2(128) NOT NULL,
    scanner_version VARCHAR2(100) NOT NULL,
    benchmark_version VARCHAR2(100) NOT NULL,
    normalizer_version VARCHAR2(100),
    configuration_version VARCHAR2(128) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    canonical_json CLOB NOT NULL CHECK (canonical_json IS JSON),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_finding_observation PRIMARY KEY (observation_id),
    CONSTRAINT fk_observation_finding FOREIGN KEY (finding_id)
        REFERENCES canonical_finding (finding_id),
    CONSTRAINT fk_observation_run FOREIGN KEY (run_id)
        REFERENCES scan_run (run_id),
    CONSTRAINT uq_finding_observation_source UNIQUE (
        finding_id,
        run_id,
        source_file,
        source_row
    )
);

CREATE INDEX ix_canonical_stage_run ON canonical_finding_stage (run_id);
CREATE INDEX ix_canonical_finding_scope ON canonical_finding (
    tenancy_id,
    benchmark_version,
    control_display_id,
    scope_type,
    region_key
);
CREATE INDEX ix_finding_observation_run ON finding_observation (run_id);
