-- Product and compartment mapping scaffold.
-- This migration establishes governed product mapping inputs and placeholder
-- views before tag-inheritance implementation is hardened with live snapshots.

CREATE TABLE product_registry (
    product_id VARCHAR2(128) NOT NULL,
    display_name VARCHAR2(255) NOT NULL,
    business_owner VARCHAR2(255),
    technical_owner VARCHAR2(255),
    environment_default VARCHAR2(80),
    sla_policy VARCHAR2(128),
    routing_target VARCHAR2(255),
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_product_registry PRIMARY KEY (product_id),
    CONSTRAINT ck_product_registry_status CHECK (
        status IN ('ACTIVE', 'RETIRED')
    )
);

CREATE TABLE compartment_snapshot (
    compartment_id VARCHAR2(255) NOT NULL,
    tenancy_id VARCHAR2(255) NOT NULL,
    parent_compartment_id VARCHAR2(255),
    display_name VARCHAR2(255) NOT NULL,
    compartment_path VARCHAR2(2000) NOT NULL,
    depth NUMBER NOT NULL,
    lifecycle_state VARCHAR2(80),
    snapshot_run_id VARCHAR2(128),
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_compartment_snapshot PRIMARY KEY (compartment_id),
    CONSTRAINT fk_compartment_snapshot_run FOREIGN KEY (snapshot_run_id)
        REFERENCES scan_run (run_id)
);

CREATE TABLE compartment_product_tag (
    compartment_id VARCHAR2(255) NOT NULL,
    tag_namespace VARCHAR2(128) NOT NULL,
    tag_key VARCHAR2(128) NOT NULL,
    tag_value VARCHAR2(255) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_compartment_product_tag PRIMARY KEY (
        compartment_id,
        tag_namespace,
        tag_key
    ),
    CONSTRAINT fk_product_tag_compartment FOREIGN KEY (compartment_id)
        REFERENCES compartment_snapshot (compartment_id)
);

CREATE TABLE product_mapping_override (
    override_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compartment_id VARCHAR2(255) NOT NULL,
    product_id VARCHAR2(128) NOT NULL,
    reason VARCHAR2(1000) NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_product_mapping_override PRIMARY KEY (override_id),
    CONSTRAINT fk_mapping_override_compartment FOREIGN KEY (compartment_id)
        REFERENCES compartment_snapshot (compartment_id),
    CONSTRAINT fk_mapping_override_product FOREIGN KEY (product_id)
        REFERENCES product_registry (product_id),
    CONSTRAINT ck_mapping_override_status CHECK (
        status IN ('ACTIVE', 'EXPIRED', 'RETIRED')
    )
);

CREATE OR REPLACE VIEW vw_compartment_product_mapping AS
WITH ancestor_tag_candidates AS (
    SELECT
        compartment.compartment_id,
        candidate_tag.tag_namespace,
        candidate_tag.tag_key,
        candidate_tag.tag_value,
        ROW_NUMBER() OVER (
            PARTITION BY compartment.compartment_id
            ORDER BY ancestor.depth DESC
        ) AS ancestor_rank
    FROM compartment_snapshot compartment
    JOIN compartment_snapshot ancestor
        ON compartment.compartment_path LIKE ancestor.compartment_path || '/%'
    JOIN compartment_product_tag candidate_tag
        ON candidate_tag.compartment_id = ancestor.compartment_id
        AND candidate_tag.tag_namespace = 'Operations'
        AND candidate_tag.tag_key = 'ProductId'
),
nearest_ancestor_tag AS (
    SELECT
        compartment_id,
        tag_namespace,
        tag_key,
        tag_value
    FROM ancestor_tag_candidates
    WHERE ancestor_rank = 1
)
SELECT
    compartment.compartment_id,
    compartment.tenancy_id,
    compartment.parent_compartment_id,
    compartment.display_name AS compartment_name,
    compartment.compartment_path,
    compartment.depth,
    COALESCE(
        active_override.product_id,
        current_product.product_id,
        ancestor_product.product_id,
        'UNASSIGNED'
    ) AS effective_product_id,
    COALESCE(
        override_product.display_name,
        current_product.display_name,
        ancestor_product.display_name,
        'Unassigned'
    ) AS effective_product_name,
    CASE
        WHEN active_override.product_id IS NOT NULL THEN 'EXPLICIT_OVERRIDE'
        WHEN current_product.product_id IS NOT NULL THEN 'CURRENT_COMPARTMENT_TAG'
        WHEN ancestor_product.product_id IS NOT NULL THEN 'ANCESTOR_COMPARTMENT_TAG'
        ELSE 'UNASSIGNED'
    END AS mapping_source,
    CASE
        WHEN active_override.product_id IS NOT NULL THEN 'VALID'
        WHEN current_tag.tag_value IS NOT NULL AND current_product.product_id IS NULL THEN 'UNKNOWN_TAG'
        WHEN ancestor_tag.tag_value IS NOT NULL AND ancestor_product.product_id IS NULL THEN 'UNKNOWN_TAG'
        WHEN current_product.product_id IS NOT NULL THEN 'VALID'
        WHEN ancestor_product.product_id IS NOT NULL THEN 'VALID'
        ELSE 'MISSING'
    END AS mapping_quality_status,
    COALESCE(current_tag.tag_namespace, ancestor_tag.tag_namespace, 'Operations')
        AS tag_namespace,
    COALESCE(current_tag.tag_key, ancestor_tag.tag_key, 'ProductId') AS tag_key,
    COALESCE(current_tag.tag_value, ancestor_tag.tag_value) AS tag_value,
    active_override.override_id,
    active_override.reason AS override_reason
FROM compartment_snapshot compartment
LEFT JOIN product_mapping_override active_override
    ON active_override.compartment_id = compartment.compartment_id
    AND active_override.status = 'ACTIVE'
    AND (active_override.expires_at IS NULL OR active_override.expires_at > SYSTIMESTAMP)
LEFT JOIN product_registry override_product
    ON override_product.product_id = active_override.product_id
    AND override_product.status = 'ACTIVE'
LEFT JOIN compartment_product_tag current_tag
    ON current_tag.compartment_id = compartment.compartment_id
    AND current_tag.tag_namespace = 'Operations'
    AND current_tag.tag_key = 'ProductId'
LEFT JOIN product_registry current_product
    ON current_product.product_id = current_tag.tag_value
    AND current_product.status = 'ACTIVE'
LEFT JOIN nearest_ancestor_tag ancestor_tag
    ON ancestor_tag.compartment_id = compartment.compartment_id
LEFT JOIN product_registry ancestor_product
    ON ancestor_product.product_id = ancestor_tag.tag_value
    AND ancestor_product.status = 'ACTIVE';

CREATE OR REPLACE VIEW vw_mapping_quality AS
SELECT
    mapping.compartment_id,
    mapping.tenancy_id,
    mapping.compartment_name,
    mapping.compartment_path,
    mapping.effective_product_id,
    mapping.effective_product_name,
    mapping.mapping_source,
    mapping.mapping_quality_status,
    mapping.tag_namespace,
    mapping.tag_key,
    mapping.tag_value,
    mapping.override_id,
    mapping.override_reason
FROM vw_compartment_product_mapping mapping;

CREATE OR REPLACE VIEW vw_finding_product_placeholder AS
SELECT
    finding.finding_id,
    JSON_VALUE(finding.compartment_json, '$.ocid') AS compartment_id,
    mapping.effective_product_id,
    mapping.effective_product_name,
    mapping.mapping_source,
    mapping.mapping_quality_status
FROM canonical_finding finding
LEFT JOIN vw_compartment_product_mapping mapping
    ON mapping.compartment_id = JSON_VALUE(finding.compartment_json, '$.ocid');
