-- External integration outbox scaffold.

CREATE TABLE integration_outbox (
    integration_event_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    finding_id VARCHAR2(128) NOT NULL,
    event_type VARCHAR2(80) NOT NULL,
    target_system VARCHAR2(128) NOT NULL,
    idempotency_key VARCHAR2(255) NOT NULL,
    payload_json CLOB NOT NULL CHECK (payload_json IS JSON),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    attempt_count NUMBER DEFAULT 0 NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    external_record_id VARCHAR2(255),
    error_message VARCHAR2(2000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_integration_outbox PRIMARY KEY (integration_event_id),
    CONSTRAINT fk_outbox_finding FOREIGN KEY (finding_id)
        REFERENCES canonical_finding (finding_id),
    CONSTRAINT uq_outbox_idempotency UNIQUE (target_system, idempotency_key),
    CONSTRAINT ck_outbox_status CHECK (
        status IN ('PENDING', 'DELIVERED', 'RETRY', 'FAILED', 'DEAD_LETTER')
    )
);

CREATE INDEX ix_outbox_status_next_attempt ON integration_outbox (status, next_attempt_at);
CREATE INDEX ix_outbox_finding ON integration_outbox (finding_id);
