-- Native CIS evidence artifact downloads.
-- Original report files remain audit evidence; this cache gives APEX/ORDS a
-- clickable download path without exposing private Object Storage locators.

whenever sqlerror exit sql.sqlcode rollback

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE cis_evidence_artifact_cache (
    artifact_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id VARCHAR2(128) NOT NULL,
    source_path VARCHAR2(1024) NOT NULL,
    artifact_file_name VARCHAR2(512) NOT NULL,
    mime_type VARCHAR2(255) NOT NULL,
    checksum VARCHAR2(128) NOT NULL,
    size_bytes NUMBER NOT NULL,
    content_blob BLOB NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_cis_evidence_artifact_cache PRIMARY KEY (artifact_id),
    CONSTRAINT fk_cis_evidence_artifact_run FOREIGN KEY (run_id)
        REFERENCES scan_run (run_id),
    CONSTRAINT uq_cis_evidence_artifact_source UNIQUE (run_id, source_path),
    CONSTRAINT ck_cis_evidence_artifact_status CHECK (status IN ('ACTIVE', 'RETIRED'))
)
]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE INDEX ix_cis_evidence_artifact_run
    ON cis_evidence_artifact_cache (run_id)
]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE VIEW v_cis_evidence_artifact_downloads AS
SELECT
    artifact.artifact_id,
    artifact.run_id,
    artifact.source_path,
    artifact.artifact_file_name,
    artifact.mime_type,
    artifact.checksum,
    artifact.size_bytes,
    artifact.status,
    CASE
        WHEN (LOWER(artifact.source_path) LIKE '%_cis_summary_report.html' OR LOWER(artifact.source_path) LIKE '%/cis_summary_report.html')
            THEN 'NATIVE_HTML_SUMMARY'
        WHEN (LOWER(artifact.source_path) LIKE '%_cis_summary_report.csv' OR LOWER(artifact.source_path) LIKE '%/cis_summary_report.csv')
            THEN 'NATIVE_SUMMARY_CSV'
        WHEN (LOWER(artifact.source_path) LIKE '%_error_report.csv' OR LOWER(artifact.source_path) LIKE '%/error_report.csv')
            THEN 'NATIVE_ERROR_CSV'
        WHEN LOWER(artifact.source_path) LIKE '%.csv'
            THEN 'NATIVE_DETAIL_CSV'
        WHEN LOWER(artifact.source_path) LIKE '%.png'
            THEN 'NATIVE_CHART_IMAGE'
        WHEN LOWER(artifact.source_path) LIKE '%.jsonl'
            THEN 'NORMALIZED_AUDIT_JSONL'
        ELSE 'NATIVE_REPORT_ARTIFACT'
    END AS artifact_role,
    'artifact:' || artifact.run_id || ':' || artifact.source_path
        AS source_artifact_locator,
    '/ords/oci_cis_app/cis-evidence/artifact/' || artifact.artifact_id
        AS download_url
FROM cis_evidence_artifact_cache artifact
WHERE artifact.status = 'ACTIVE';

CREATE OR REPLACE VIEW v_cis_apex_finding_detail AS
WITH artifact_roles AS (
    SELECT
        run_id,
        MAX(CASE WHEN artifact_role = 'NATIVE_HTML_SUMMARY' THEN download_url END)
            AS native_html_summary_download_url,
        MAX(CASE WHEN artifact_role = 'NATIVE_SUMMARY_CSV' THEN download_url END)
            AS native_summary_csv_download_url,
        MAX(CASE WHEN artifact_role = 'NATIVE_ERROR_CSV' THEN download_url END)
            AS native_error_csv_download_url
    FROM v_cis_evidence_artifact_downloads
    GROUP BY run_id
)
SELECT
    queue.finding_id,
    queue.tenancy_id,
    queue.control_display_id,
    queue.control_lineage_id,
    queue.benchmark_version,
    queue.current_state,
    queue.priority,
    queue.risk_score,
    queue.owner,
    queue.product_id,
    queue.product_display_name,
    queue.product_mapping_source,
    queue.resource_type,
    queue.resource_name,
    queue.region,
    queue.compartment_ocid,
    queue.compartment_name,
    queue.compartment_path,
    queue.last_observed_run_id,
    queue.last_source_file,
    queue.last_source_row,
    queue.last_schema_hash,
    queue.first_seen_at,
    queue.last_seen_at,
    queue.due_at,
    queue.due_status,
    queue.age_days,
    queue.apex_detail_key,
    COALESCE(
        detail_artifact.download_url,
        artifact_roles.native_html_summary_download_url,
        audit_report.native_detail_csv_link,
        audit_report.native_html_summary_link,
        queue.evidence_locator
    ) AS evidence_locator,
    audit_report.run_status,
    audit_report.scanner_version,
    audit_report.scanner_commit,
    audit_report.wrapper_version,
    audit_report.normalizer_version,
    audit_report.configuration_version,
    audit_report.recommendation_number,
    audit_report.cis_section,
    audit_report.cis_level,
    audit_report.recommendation_title,
    audit_report.cis_result,
    audit_report.native_findings_count,
    audit_report.native_compliant_items,
    audit_report.native_total_count,
    audit_report.native_compliance_percentage,
    audit_report.evidence_summary,
    audit_report.remediation,
    audit_report.source_file AS native_source_file,
    audit_report.source_row AS native_source_row,
    audit_report.schema_hash AS native_schema_hash,
    audit_report.manifest_checksum,
    audit_report.native_html_summary_link,
    audit_report.native_summary_csv_link,
    audit_report.native_detail_csv_link,
    audit_report.native_error_csv_link,
    artifact_roles.native_html_summary_download_url,
    artifact_roles.native_summary_csv_download_url,
    detail_artifact.download_url AS native_detail_csv_download_url,
    artifact_roles.native_error_csv_download_url,
    audit_report.source_artifact_locator
FROM v_cis_apex_work_queue queue
LEFT JOIN v_cis_audit_report_view audit_report
    ON audit_report.finding_id = queue.finding_id
    AND audit_report.run_id = queue.last_observed_run_id
LEFT JOIN artifact_roles
    ON artifact_roles.run_id = queue.last_observed_run_id
LEFT JOIN v_cis_evidence_artifact_downloads detail_artifact
    ON detail_artifact.run_id = audit_report.run_id
    AND detail_artifact.artifact_file_name = audit_report.source_file
    AND detail_artifact.artifact_role = 'NATIVE_DETAIL_CSV';

CREATE OR REPLACE VIEW v_cis_apex_finding_evidence AS
SELECT
    finding_id,
    last_observed_run_id AS run_id,
    run_status,
    scanner_version,
    benchmark_version,
    wrapper_version,
    normalizer_version,
    configuration_version,
    recommendation_number,
    cis_section,
    cis_level,
    recommendation_title,
    cis_result,
    native_findings_count,
    native_compliant_items,
    native_total_count,
    native_compliance_percentage,
    evidence_summary,
    remediation,
    native_source_file,
    native_source_row,
    native_schema_hash,
    manifest_checksum,
    native_html_summary_link,
    native_summary_csv_link,
    native_detail_csv_link,
    native_error_csv_link,
    native_html_summary_download_url,
    native_summary_csv_download_url,
    native_detail_csv_download_url,
    native_error_csv_download_url,
    source_artifact_locator,
    evidence_locator
FROM v_cis_apex_finding_detail;

GRANT SELECT ON cis_evidence_artifact_cache TO oci_cis_app;
GRANT SELECT ON v_cis_evidence_artifact_downloads TO oci_cis_app;
GRANT SELECT ON v_cis_apex_finding_detail TO oci_cis_app;
GRANT SELECT ON v_cis_apex_finding_evidence TO oci_cis_app;

BEGIN
    ORDS.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'OCI_CIS_APP',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'oci_cis_app',
        p_auto_rest_auth => FALSE
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -20006 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    ORDS.DELETE_MODULE(p_module_name => 'cis-evidence');
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    ORDS.DEFINE_MODULE(
        p_module_name => 'cis-evidence',
        p_base_path => 'cis-evidence/',
        p_items_per_page => 25,
        p_status => 'PUBLISHED',
        p_comments => 'Download immutable native CIS evidence artifacts by artifact id.'
    );

    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'cis-evidence',
        p_pattern => 'artifact/:artifact_id'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name => 'cis-evidence',
        p_pattern => 'artifact/:artifact_id',
        p_method => 'GET',
        p_source_type => ORDS.source_type_plsql,
        p_source => q'[
DECLARE
    l_blob BLOB;
    l_mime_type VARCHAR2(255);
    l_file_name VARCHAR2(512);
BEGIN
    SELECT
        content_blob,
        mime_type,
        artifact_file_name
    INTO
        l_blob,
        l_mime_type,
        l_file_name
    FROM cis_evidence_artifact_cache
    WHERE artifact_id = TO_NUMBER(:artifact_id)
    AND status = 'ACTIVE';

    OWA_UTIL.mime_header(l_mime_type, FALSE);
    HTP.p('Content-Length: ' || DBMS_LOB.getlength(l_blob));
    HTP.p('Content-Disposition: inline; filename="' || REPLACE(l_file_name, '"', '') || '"');
    OWA_UTIL.http_header_close;
    WPG_DOCLOAD.download_file(l_blob);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        :status_code := 404;
        OWA_UTIL.mime_header('text/plain', FALSE);
        OWA_UTIL.http_header_close;
        HTP.p('Artifact not found');
    WHEN VALUE_ERROR THEN
        :status_code := 400;
        OWA_UTIL.mime_header('text/plain', FALSE);
        OWA_UTIL.http_header_close;
        HTP.p('Invalid artifact id');
END;
]',
        p_items_per_page => 0,
        p_comments => 'Streams a cached native CIS report artifact.'
    );

    COMMIT;
END;
/
