#!/usr/bin/env python3
"""Build a local ADB SQL deployment package from ordered migrations.

The package is a handoff artifact only. It does not connect to ADB, read
credentials, create wallets, or apply migrations.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = ROOT / "database" / "migrations"
DEFAULT_OUTPUT_DIR = Path("/tmp/oci-cis-adb-deploy")
BUNDLE_NAME = "phase3_adb_migration_bundle.sql"
MANIFEST_NAME = "phase3_adb_deploy_manifest.json"
README_NAME = "README.md"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ordered_migrations(migrations_dir: Path = MIGRATIONS) -> list[Path]:
    return sorted(migrations_dir.glob("V*.sql"))


def build_bundle_sql(migrations: Sequence[Path]) -> str:
    lines = [
        "-- OCI CIS Findings Operations Hub Phase 3 ADB migration bundle",
        "-- Generated from repository migrations for DBA review and controlled execution.",
        "-- Do not paste credentials, wallets, tokens, or native CIS output into this file.",
        "set define off",
        "set sqlblanklines on",
        "whenever sqlerror exit sql.sqlcode rollback",
        "prompt Starting Phase 3 migration bundle",
        "",
    ]
    for migration in migrations:
        lines.extend(
            [
                f"prompt Applying {migration.name}",
                f"-- BEGIN {migration.name}",
                migration.read_text(encoding="utf-8").rstrip(),
                f"-- END {migration.name}",
                "",
            ],
        )
    lines.extend(
        [
            "prompt Phase 3 migration bundle complete",
            "exit success",
            "",
        ],
    )
    return "\n".join(lines)


def build_manifest(migrations: Sequence[Path]) -> dict[str, object]:
    return {
        "package": "oci-cis-findings-op-phase3-adb",
        "bundle": BUNDLE_NAME,
        "migrationCount": len(migrations),
        "migrations": [
            {
                "file": migration.relative_to(ROOT).as_posix(),
                "sha256": "sha256:" + sha256_file(migration),
            }
            for migration in migrations
        ],
        "boundaries": {
            "connectsToAdb": False,
            "requiresCredentials": False,
            "containsNativeCisRows": False,
            "containsWallet": False,
        },
    }


def build_readme() -> str:
    return """# Phase 3 ADB Deployment Package

This directory is generated by `scripts/build_adb_deploy_package.py`.

Contents:

- `phase3_adb_migration_bundle.sql`: ordered SQL migration bundle for DBA-controlled execution.
- `phase3_adb_deploy_manifest.json`: migration file list and SHA-256 hashes.

Execution boundary:

- The generator does not connect to Autonomous Database.
- The package contains no wallet, password, token, private key, or native CIS output.
- Run the bundle only from an approved SQLcl/sqlplus environment with credentials stored outside Git.

Example controlled execution:

```bash
sql -cloudconfig /secure/path/wallet.zip '<user>/<password>@<adb_service>' @phase3_adb_migration_bundle.sql
```

Do not commit generated deployment packages if they are combined with logs, spool files, wallets, or
environment-specific connection material.
"""


def build_package(output_dir: Path, migrations_dir: Path = MIGRATIONS) -> dict[str, object]:
    migrations = ordered_migrations(migrations_dir)
    if not migrations:
        raise ValueError(f"no migrations found under {migrations_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    bundle_path = output_dir / BUNDLE_NAME
    manifest_path = output_dir / MANIFEST_NAME
    readme_path = output_dir / README_NAME

    bundle_path.write_text(build_bundle_sql(migrations), encoding="utf-8")
    manifest = build_manifest(migrations)
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    readme_path.write_text(build_readme(), encoding="utf-8")

    return {
        "outputDir": output_dir.as_posix(),
        "bundle": bundle_path.as_posix(),
        "manifest": manifest_path.as_posix(),
        "migrationCount": len(migrations),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)

    result = build_package(args.output_dir)
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
